version: '3.8'

services:
  app:
    build: .
    container_name: devops-demo-app
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.0.105:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3